name: obsidian2hexo-deploy-actions
# 把 obsidian 转换成博客
on:
  push:
    branches:
      # 监听 master 分支如果有变动调用当前Actions
      - master
# 环境变量
env:
  HEXO_TEMPLATE: 7zMonkey/obsidian2hexo-template
  BLOG: git@github.com:7zMonkey/7zMonkey.github.io.git
jobs:
# 拉取 hexo 模板
  obsidian2hexo-deploy-actions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          repository: ${{ env.HEXO_TEMPLATE }}
          path: hexo-template

      - name: Checkout code
        uses: actions/checkout@v2
        with:
          path: obsidian-doc

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: cd hexo-template
        run: cd hexo-template

      - name: Install node_modules
        run: npm install

      - name: Install hexo-cli
        run: npm install -g hexo-cli

      - name: ls
        run: ls -a

      - name: cd hexo-template
        run: cd hexo-template

      - name: Hexo generate
        run: hexo generate

      - name: Display Git version
        run: git --version
        
      - name: Git clone
        run: git clone ${{ env.BLOG }} blog --depth 1
        # run 后面跟随 git 拉取的仓库 目标路径改为blog
      - name: Move Generate Files
        run: mv hexo-template/public ~/blog

      - name: Run Git commands
        run: |
          git status
          git add .
          git commit -m ":rocket:display: $(date)"
          git push