name: obsidian2hexo-deploy-actions
# 把 obsidian 转换成博客
on:
  push:
    branches:
      # 监听 master 分支如果有变动调用当前Actions
      - master
# 环境变量
env:
  HEXO_TEMPLATE: 7zMonkey/obsidian2hexo-template
  BLOG: 7zMonkey/7zMonkey.github.io
jobs:
# 拉取 hexo 模板
  obsidian2hexo-deploy-actions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          repository: ${{ env.HEXO_TEMPLATE }}
          path: hexo-template

      - name: Checkout code
        uses: actions/checkout@v2
        with:
          path: obsidian-doc

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Hexo generate
        run: |
          cd hexo-template
          npm install
          npm install -g hexo-cli
          hexo generate

      - name: Display Git version
        run: git --version
        
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          repository: ${{ env.BLOG }}
          path: blog
        # run 后面跟随 git 拉取的仓库 目标路径改为blog

      - name: Move Generate Files
        run: mv hexo-template/public blog
      
      - name: Ls
        run: ls -a blog

      - name: Write to ~/.ssh/id_rsa
        run: |
          mkdir -p ~/.ssh/
          echo "${{ secrets.DEPLOY_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts

      - name: Run Git commands
        run: |
          cd blog
          ls
          git status
          git add .
          git commit -m ":rocket:display: $(date)"
          git push